dna_codon_aa <- data.frame(one_letter = c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", 
                                          "N", "P", "Q", "R", "S", "T", "V", "W", "Y", " "),
                           three_letter = c("Ala", "Cys", "Asp", "Glu", "Phe", "Gly", "His", "Ile", "Lys", "Leu", "Met", 
                                            "Asn", "Pro", "Gln", "Arg", "Ser", "Thr", "Val", "Trp", "Tyr", "  "),
                           aminoacid = c("Alanine", "Cysteine", "Aspartic acid", "Glutamic acid", "Phenylalanine", "Glycine", "Histidine", "Isoleucine", "Lysine", "Leucine", "Methionine", 
                                         "Asparagine", "Proline", "Glutamine", "Arginine", "Serine", "Threonine", "Valine", "Tryptophan", "Tyrosine", " "),
                           Human       = c("GCC", "TGC", "GAC", "GAG", "TTC", "GGC", "CAC", "ATC", "AAG", "CTG", "ATG", 
                                           "AAC", "CCC", "CAG", "CGG", "AGC", "ACC", "GTG", "TGG", "TAC", "  "),
                           Mouse       = c("GCC", "TGC", "GAC", "GAG", "TTC", "GGC", "CAC", "ATC", "AAG", "CTG", "ATG", 
                                           "AAC", "CCC", "CAG", "AGG", "AGC", "ACC", "GTG", "TGG", "TAC", "  "),
                           Celegans    = c("GCT", "TGT", "GAT", "GAA", "TTT", "GGA", "CAT", "ATT", "AAA", "CTT", "ATG",
                                           "AAT", "CCA", "CAA", "AGA", "TCA", "ACA", "GTT", "TGG", "TAT", "  "),
                           Athaliana   = c("GCT", "TGT", "GAT", "GAA", "TTT", "GGA", "CAT", "ATT", "AAG", "CTT", "ATG",
                                           "AAT", "CCT", "CAA", "AGA", "TCT", "ACT", "GTT", "TGG", "TAT", "  "), 
                           Ecoli       = c("GCG", "TGC", "GAT", "GAA", "TTT", "GGC", "CAT", "ATT", "AAA", "CTG", "ATG",
                                           "AAC", "CCG", "CAG", "CGT", "AGC", "ACC", "GTG", "TGG", "TAT", "  "),
                           stringsAsFactors = F)

rna_codon_aa <- data.frame(one_letter = c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", 
                                          "N", "P", "Q", "R", "S", "T", "V", "W", "Y", " "),
                           three_letter = c("Ala", "Cys", "Asp", "Glu", "Phe", "Gly", "His", "Ile", "Lys", "Leu", "Met", 
                                            "Asn", "Pro", "Gln", "Arg", "Ser", "Thr", "Val", "Trp", "Tyr", "  "),
                           aminoacid = c("Alanine", "Cysteine", "Aspartic acid", "Glutamic acid", "Phenylalanine", "Glycine", "Histidine", "Isoleucine", "Lysine", "Leucine", "Methionine", 
                                         "Asparagine", "Proline", "Glutamine", "Arginine", "Serine", "Threonine", "Valine", "Tryptophan", "Tyrosine", " "),
                           Human       = c("GCC", "UGC", "GAC", "GAG", "UUC", "GGC", "CAC", "AUC", "AAG", "CUG", "AUG", 
                                           "AAC", "CCC", "CAG", "CGG", "AGC", "ACC", "GUG", "UGG", "UAC", "  "),
                           Mouse       = c("GCC", "UGC", "GAC", "GAG", "UUC", "GGC", "CAC", "AUC", "AAG", "CUG", "AUG", 
                                           "AAC", "CCC", "CAG", "AGG", "AGC", "ACC", "GUG", "UGG", "UAC", "  "),
                           Celegans    = c("GCU", "UGU", "GAU", "GAA", "UUU", "GGA", "CAU", "AUU", "AAA", "CUU", "AUG",
                                           "AAU", "CCA", "CAA", "AGA", "UCA", "ACA", "GUU", "UGG", "UAU", "  "),
                           Athaliana   = c("GCU", "UGU", "GAU", "GAA", "UUU", "GGA", "CAU", "AUU", "AAG", "CUU", "AUG",
                                           "AAU", "CCU", "CAA", "AGA", "UCU", "ACU", "GUU", "UGG", "UAU", "  "), 
                           Ecoli       = c("GCG", "UGC", "GAU", "GAA", "UUU", "GGC", "CAU", "AUU", "AAA", "CUG", "AUG",
                                           "AAC", "CCG", "CAG", "CGU", "AGC", "ACC", "GUG", "UGG", "UAU", "  "),
                           stringsAsFactors = F)